"""add activity lvl1

Revision ID: 50be3adc19a5
Revises: e3059808a3e2
Create Date: 2026-05-20 22:18:13.477679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50be3adc19a5'
down_revision: Union[str, Sequence[str], None] = 'e3059808a3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activity_level', sa.String(length=32), nullable=False, server_default="обычный"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activity_level')
    # ### end Alembic commands ###
