"""add profile fields

Revision ID: 85a0d2009b48
Revises: f86621527287
Create Date: 2026-05-16 22:32:09.437423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a0d2009b48'
down_revision: Union[str, Sequence[str], None] = 'f86621527287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('current_weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('goal_weight', sa.Float(), nullable=True))
    op.execute("UPDATE users SET profile_name = '', current_weight = 0.0, goal_weight = 0.0")
    op.alter_column('users', 'profile_name', nullable=False)
    op.alter_column('users', 'current_weight', nullable=False)
    op.alter_column('users', 'goal_weight', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_weight')
    op.drop_column('users', 'current_weight')
    op.drop_column('users', 'profile_name')
    # ### end Alembic commands ###
