"""add age and height for users

Revision ID: e3059808a3e2
Revises: f4d0172ff9d5
Create Date: 2026-05-20 21:22:34.588847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3059808a3e2'
down_revision: Union[str, Sequence[str], None] = 'f4d0172ff9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'height')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
